[package]
name = "ohos-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctor = "0.2.5"
sys = {path='../sys'}
back-macro = {path='../back-macro'}

[lib]
crate-type = ["cdylib"]
